version: '3.5'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: ../../docker/frontend/Dockerfile.dev
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: ./src/backend
      dockerfile: ../../docker/backend/Dockerfile.dev
    volumes:
      - ./src/backend:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: