version: '3.5'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: ../../docker/frontend/Dockerfile.prod
    networks:
      - app-network

  backend:
    build:
      context: ./src/backend
      dockerfile: ../../docker/backend/Dockerfile.prod
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: