global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    dns_sd_configs:
      - names:
        - 'tasks.backend'
        type: 'A'
        port: 9000

  - job_name: 'frontend'
    dns_sd_configs:
      - names:
        - 'tasks.frontend'
        type: 'A'
        port: 80